version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cli
    main: ./apps/cli
    binary: pics
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: cli-archives
    name_template: >-
      {{ .ProjectName }}-cli_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  github:
    owner: acm19
    name: pics
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### CLI (pics)
    Lightweight command-line tool.

    **Linux/macOS:**
    ```bash
    # Extract the archive
    tar -xzf pics-cli_*.tar.gz

    # Make executable and move to PATH
    chmod +x pics
    sudo mv pics /usr/local/bin/

    # Verify installation
    pics --version
    ```

    **Windows:**
    Extract `pics-cli_Windows_*.zip` and add `pics.exe` to your PATH.

    ### Desktop UI (pics-ui)
    Full-featured desktop application with bundled dependencies (coming soon).

    ### Dependencies (CLI only)
    - **ExifTool**: Required for EXIF data extraction.
    - **jpegoptim**: Required for JPEG compression (optional).

  footer: |
    **Full Changelog**: https://github.com/acm19/pics/compare/{{ .PreviousTag }}...{{ .Tag }}
