coverage:
  status:
    project:
      default:
        target: auto
        threshold: 100%
        informational: true
    patch:
      default:
        target: auto
        threshold: 100%
        informational: true

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
